module.exports = {
  RECEIVE_DEFAULT_PROJECT: 'RECEIVE_DEFAULT_PROJECT',
  RECEIVE_COLLECTION_DATA: 'RECEIVE_COLLECTION_DATA',
  RECEIVE_COLLECTIONS: 'RECEIVE_COLLECTIONS',
  RECEIVE_NEW_COLLECTION: 'RECEIVE_NEW_COLLECTION',
  SET_ACTIVE_COLLECTION: 'SET_ACTIVE_COLLECTION',
  COLLECTION_FORM: 'COLLECTION_FORM',
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
};
